blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path("", views.index, name="index"),
    path("page/<int:page_number>/", views.index, name="page"),
    path("article/<slug:slug>/", views.article_view, name="article"),
    path(
        "article/<slug:slug>/compose-comment/",
        views.comment_compose,
        name="compose-comment",
    ),
    path(
        "article/<slug:slug>/submit-comment/",
        views.comment_submit,
        name="submit-comment",
    ),
    path("approve-comment/<int:id>/", views.comment_approve, name="approve-comment"),
    path("tag/<str:tag_name>/", views.tag_view, name="tag"),
    path("tag/<str:tag_name>/page/<int:page_number>/", views.tag_view, name="tag_page"),
    path("rss/", views.ArticlesFeed(), name="rss"),
    path("gmi_index/", views.gmi_index, name="gmi_index"),
    path("gmi_article/<slug:slug>/", views.gmi_article_view, name="gmi_article"),
]

guestbook/urls.py
from django.urls import path
from . import views

app_name = "guestbook"
urlpatterns = [
    path("", views.index, name="index"),
    path("submit/", views.submit, name="submit"),
]

hamsterdance/urls.py
from django.contrib import admin
from django.urls import include, path

admin.autodiscover()

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls"), name="blog"),
    path("guestbook/", include("guestbook.urls"), name="guestbook"),
    path("podcast/", include("podcast.urls"), name="podcast"),
]

guestbook/models.py
from email.message import EmailMessage
import logging
import smtplib
from django.db import models
from django.dispatch import receiver
from hamsterdance import settings


class Entry(models.Model):
    message = models.CharField(blank=False, max_length=1024)
    name = models.CharField(blank=True, max_length=256)
    date = models.DateTimeField(auto_now_add=True)


@receiver(models.signals.post_save, sender=Entry)
def email_on_signing(sender, instance, created, **kwargs):
    if not created:
        return
    msg = EmailMessage()
    msg["From"] = f"{settings.HOST_DOMAIN} <no-reply@{settings.HOST_DOMAIN}>"
    msg["To"] = "Dominique Cyprès <lunasspecto@hamster.dance>"
    msg["Subject"] = "New guestbook entry"
    msg.set_content(
        "Someone has signed the guestbook.\n"
        f"name: {instance.name}\n"
        f"message: {instance.message}"
    )
    try:
        with smtplib.SMTP("localhost", 1025 if settings.DEBUG else 25) as smtp:
            smtp.send_message(msg)
    except Exception:
        log = logging.getLogger()
        log.warning(
            "Unable to send email notification of comment creation", exc_info=True
        )

guestbook/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .models import Entry


def index(request):
    return render(
        request,
        "guestbook/index.html",
        {"guestbook_entries": Entry.objects.order_by("-date")},
    )


def submit(request):
    if (
        request.method == "POST"
        and request.POST.get("spam", "1") == "0"
        and request.POST.get("message")
    ):
        Entry.objects.create(
            message=request.POST["message"], name=request.POST.get("name", "")
        )
    return HttpResponseRedirect("../")

guestbook/templates/guestbook/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link href="/lunasspecto.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>hamster.dance guestbook</title>
  </head>
  <body>
    <h1>hamster.dance guestbook</h1>
    <form action="{% url 'guestbook:submit' %}" method="post">
      {% csrf_token %}
      <label for="message-input">Message:</label>
      <br />
      <textarea
        id="message-input"
        name="message"
        cols="40"
        rows="4"
        minlength="1"
        maxlength="1024"
        required="true"
      ></textarea>
      <br />
      <label for="name-input">Name (optional):</label>
      <br />
      <input
        type="text"
        id="name-input"
        name="name"
        maxlength="256"
      />
      <br />
      <label for="spam-select">
          Describe the spam content of your message:
      </label>
      <br />
      <select id="spam-select" name="spam">
        <option value="1">well, it hasn't got MUCH spam in it</option>
        <option value="1">spam, eggs, bacon &amp; spam</option>
        <option value="0">absolutely zero spam</option>
        <option value="1">spam, egg, spam, spam, bacon &amp; spam</option>
        <option value="1">spam spam spam spam spam spam spam spam</option>
      </select>
      <br />
      <input type="submit" value="Sign guestbook" />
    </form>
    {% for entry in guestbook_entries %}
    <p>
      <em>{{ entry.message|escape|linebreaksbr }}</em>&mdash;{{ entry.name|escape|default:"anonymous" }}, {{ entry.date|date:"j M Y" }}
    </p>
    {% endfor %}
    <hr />
    <a href="/">home</a>
  </body>
</html>