blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path("", views.index, name="index"),
    path("page/<int:page_number>/", views.index, name="page"),
    path("article/<slug:slug>/", views.article_view, name="article"),
    path(
        "article/<slug:slug>/compose-comment/",
        views.comment_compose,
        name="compose-comment",
    ),
    path(
        "article/<slug:slug>/submit-comment/",
        views.comment_submit,
        name="submit-comment",
    ),
    path("approve-comment/<int:id>/", views.comment_approve, name="approve-comment"),
    path("tag/<str:tag_name>/", views.tag_view, name="tag"),
    path("tag/<str:tag_name>/page/<int:page_number>/", views.tag_view, name="tag_page"),
    path("rss/", views.ArticlesFeed(), name="rss"),
    path("gmi_index/", views.gmi_index, name="gmi_index"),
    path("gmi_article/<slug:slug>/", views.gmi_article_view, name="gmi_article"),
]

hamsterdance/urls.py
from django.contrib import admin
from django.urls import include, path

admin.autodiscover()

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls"), name="blog"),
    path("guestbook/", include("guestbook.urls"), name="guestbook"),
    path("podcast/", include("podcast.urls"), name="podcast"),
]

podcast/urls.py
from django.urls import path
from . import views

app_name = "podcast"
urlpatterns = [
    path("", views.index, name="index"),
    path("episode/<slug:slug>/", views.episode_view, name="episode"),
]

podcast/models.py
from django.db import models


class Episode(models.Model):
    season = models.IntegerField()
    number = models.IntegerField()
    title = models.CharField(max_length=256)
    audio_url = models.CharField(max_length=256)
    description = models.CharField(max_length=256)
    published = models.DateTimeField(null=False)
    slug = models.SlugField(max_length=32, unique=True)
    transcript = models.TextField(blank=False)

    class Meta:
        ordering = ("-season", "-number")

    def __str__(self):
        return self.slug

podcast/views.py
from datetime import datetime
from django.shortcuts import get_object_or_404, render
from .models import Episode


def index(request, page_number=1):
    seasons = (
        Episode.objects.filter(published__lte=datetime.now())
        .distinct("season")
        .values_list("season", flat=2)
    )
    season_episodes = {
        season: Episode.objects.filter(published__lte=datetime.now(), season=season)
        for season in seasons
    }
    return render(
        request,
        "podcast/index.html",
        {"seasons": seasons, "season_episodes": season_episodes},
    )


def episode_view(request, slug=""):
    episode = get_object_or_404(Episode, slug=slug, published__lte=datetime.now())
    return render(request, "podcast/episode.html", {"episode": episode})

podcast/templates/podcast/episode.html
{% load podcast_extras %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link href="/lunasspecto.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{{ episode.title }}&mdash;The World on a Wire Show</title>
  </head>
  <body>
    <p>
        <audio controls src="{{ episode.audio_url|safe }}">
          <a download href="{{ episode.audio_url|safe }}">Download this episode.</a>
        </audio>
    </p>
    {{ episode.transcript|markdown|safe }}
    <footer>
      <hr />
      <a href="/">home</a>
      &gt;
      <a href="/podcast/">podcast</a>
    </footer>
  </body>
</html>

podcast/templates/podcast/index.html
{% load podcast_extras %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link href="/lunasspecto.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>The World on a Wire Show</title>
  </head>
  <body>
    <h1>The World on a Wire Show</h1>
    <p>
      <em>The World on a Wire Show</em> is my podcast that explores the social
      history of computing. All episodes and their transcripts are linked below.
      The show is also available for listening through various podcatcher
      services; it is currently
      <a href="https://worldonawireshow.podbean.com/">
	hosted on Podbean
      </a>
      and there is an
      <a href="https://feed.podbean.com/worldonawireshow/feed.xml">
	RSS feed
      </a>
      available.
    </p>
    {% for season in seasons %}
      <h2>Season {{ season }}</h2>
      {% for episode in season_episodes|get:season %}
        <h3><a href="{% url 'podcast:episode' episode.slug %}">
          Episode {{ episode.number }}: {{episode.title}}
        </a></h3>
        <p>{{ episode.description }}</p>
      {% endfor %}
    {% endfor %}
    <footer>
      <hr />
      <a href="/">home</a>
    </footer>
  </body>
</html>