blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path("", views.index, name="index"),
    path("page/<int:page_number>/", views.index, name="page"),
    path("article/<slug:slug>/", views.article_view, name="article"),
    path(
        "article/<slug:slug>/compose-comment/",
        views.comment_compose,
        name="compose-comment",
    ),
    path(
        "article/<slug:slug>/submit-comment/",
        views.comment_submit,
        name="submit-comment",
    ),
    path("approve-comment/<int:id>/", views.comment_approve, name="approve-comment"),
    path("tag/<str:tag_name>/", views.tag_view, name="tag"),
    path("tag/<str:tag_name>/page/<int:page_number>/", views.tag_view, name="tag_page"),
    path("rss/", views.ArticlesFeed(), name="rss"),
    path("gmi_index/", views.gmi_index, name="gmi_index"),
    path("gmi_article/<slug:slug>/", views.gmi_article_view, name="gmi_article"),
]

hamsterdance/urls.py
from django.contrib import admin
from django.urls import include, path

admin.autodiscover()

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls"), name="blog"),
    path("guestbook/", include("guestbook.urls"), name="guestbook"),
    path("podcast/", include("podcast.urls"), name="podcast"),
]

blog/models.py
from email.message import EmailMessage
import logging
import secrets
import smtplib
from django.db import models
from django.dispatch import receiver
from hamsterdance import settings


class Tag(models.Model):
    name = models.CharField(blank=False, max_length=128, unique=True)

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(blank=True, max_length=256)
    description = models.CharField(max_length=256)
    body = models.TextField(blank=False)
    slug = models.SlugField(max_length=32, unique=True)
    tags = models.ManyToManyField(Tag)
    published = models.DateTimeField(null=False)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.slug


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    body = models.CharField(blank=False, max_length=5096)
    name = models.CharField(blank=True, max_length=256)
    approved = models.BooleanField(default=False)
    token = models.CharField(blank=False, max_length=256, default=secrets.token_urlsafe)
    created = models.DateTimeField(auto_now_add=True)


@receiver(models.signals.post_save, sender=Comment)
def email_on_comment(sender, instance, created, **kwargs):
    if (not created) or instance.approved:
        return
    msg = EmailMessage()
    msg["From"] = f"{settings.HOST_DOMAIN} <no-reply@{settings.HOST_DOMAIN}>"
    msg["To"] = "Dominique Cyprès <lunasspecto@hamster.dance>"
    msg["Subject"] = "New comment awaiting approval"
    msg.set_content(
        "Someone has left a comment on a blog article.\n"
        f"article: {instance.article.title}\n"
        f"name: {instance.name}\n"
        f"body: {instance.body}\n\n"
        "To approve this comment, visit\n"
        f"https://{settings.HOST_DOMAIN}/blog/approve-comment/{instance.id}/?token={instance.token}"
    )
    try:
        with smtplib.SMTP("localhost", 1025 if settings.DEBUG else 25) as smtp:
            smtp.send_message(msg)
    except Exception:
        log = logging.getLogger()
        log.warning(
            "Unable to send email notification of comment creation", exc_info=True
        )

blog/views.py
from datetime import datetime
from html import unescape
import logging
import secrets
from django.contrib.syndication.views import Feed
from django.http import Http404, HttpResponseNotAllowed, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.feedgenerator import Rss201rev2Feed
from django.utils.html import strip_tags
from markdown import markdown
from .models import Article, Comment, Tag
from hamsterdance import settings


def index(request, page_number=1):
    articles = Article.objects.filter(published__lte=datetime.now()).order_by(
        "-published"
    )
    valid_number = page_number > 0 and ((page_number - 1) * 20) < len(articles)
    if valid_number:
        return render(
            request,
            "blog/index.html",
            {
                "articles": articles[20 * (page_number - 1) : 20 * page_number],
                "last_page": (20 * page_number) >= len(articles),
                "next_page": page_number + 1,
                "page_number": page_number,
                "previous_page": page_number - 1,
            },
        )
    else:
        raise Http404("Invalid page number")


def article_view(request, slug=""):
    article = get_object_or_404(Article, slug=slug, published__lte=datetime.now())
    comments = Comment.objects.filter(approved=True, article=article).order_by(
        "created"
    )
    comments_total = len(comments)
    tags = article.tags.all()
    return render(
        request,
        "blog/article.html",
        {
            "article": article,
            "comments": comments,
            "comments_total": comments_total,
            "tags": tags,
        },
    )


def comment_compose(request, slug=""):
    article = get_object_or_404(Article, slug=slug, published__lte=datetime.now())
    return render(request, "blog/compose-comment.html", {"article": article})


def comment_submit(request, slug=""):
    article = get_object_or_404(Article, slug=slug, published__lte=datetime.now())
    if request.method != "POST":
        return render(
            request, "blog/comment-failed.html", {"article": article}, status=405
        )
    if request.POST.get("spam", "1") == "0" and request.POST.get("body"):
        Comment.objects.create(
            article=article,
            body=request.POST["body"],
            name=request.POST.get("name", ""),
            approved=False,
        )
        return render(request, "blog/comment-submitted.html", {"article": article})
    return render(request, "blog/comment-failed.html", {"article": article}, status=400)


def comment_approve(request, id):
    comment = get_object_or_404(Comment, id=id)
    if request.method == "GET" and secrets.compare_digest(
        request.GET.get("token", ""), comment.token
    ):
        comment.approved = True
        comment.save()
        return HttpResponseRedirect(
            reverse("blog:article", args=[comment.article.slug])
        )
    return Http403()


def tag_view(request, tag_name="", page_number=1):
    tag = get_object_or_404(Tag, name=tag_name)
    articles = Article.objects.filter(
        tags__name=tag_name, published__lte=datetime.now()
    ).order_by("-published")
    valid_number = page_number > 0 and ((page_number - 1) * 20) < len(articles)
    if valid_number:
        return render(
            request,
            "blog/tag.html",
            {
                "tag": tag,
                "articles": articles[20 * (page_number - 1) : 20 * page_number],
                "last_page": (20 * page_number) >= len(articles),
                "next_page": page_number + 1,
                "page_number": page_number,
                "previous_page": page_number - 1,
            },
        )
    else:
        raise Http404("Invalid page number")


def gmi_index(request):
    articles = Article.objects.filter(published__lte=datetime.now()).order_by(
        "-published"
    )
    return render(request, "blog/index.gmi", {"articles": articles})


def gmi_article_view(request, slug=""):
    article = get_object_or_404(Article, slug=slug, published__lte=datetime.now())
    return render(request, "blog/article.gmi", {"article": article})


class ArticlesFeed(Feed):
    title = "hamster.dance blog articles"
    link = f"https://{settings.HOST_DOMAIN}/blog/"
    description = "Articles from the hamster.dance blog."
    feed_url = f"https://{settings.HOST_DOMAIN}/blog/rss/"
    author_name = "Dominique Cyprès"
    author_email = "lunasspecto@hamster.dance"
    feed_type = Rss201rev2Feed

    def items(self):
        return Article.objects.filter(published__lte=datetime.now()).order_by(
            "-published"
        )

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.description

    def item_link(self, item):
        return f"https://{settings.HOST_DOMAIN}/blog/article/{item.slug}/"

    def item_pubdate(self, item):
        return item.published

    def item_updateddate(self, item):
        return item.modified

    def item_categories(self, item):
        return [tag.name for tag in item.tags.all()]

blog/templates/blog/article.html
{% load blog_extras %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link href="/lunasspecto.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{{ article.title|striptags }}&mdash;hamster.dance blog</title>
  </head>
  <body>
    <h1>{{ article.title|safe }}</h1>
    <p><em>
      Published {{ article.published|date:"j M Y" }},
      last modified {{ article.modified|date:"j M Y" }}
    </em></p>
    {{ article.body|markdown|safe }}
    <hr />
    <p><em>
      Tags:
      {% for tag in tags %}
      <a href="{% url 'blog:tag' tag.name %}" rel="tag">{{tag.name}}</a>
      {% endfor %}
    </em></p>
    <p>
      There {% if comments_total == 1 %}is{% else %}are{% endif %}
      {% if comments_total == 0 %}no{% else %}{{ comments_total }}{% endif %}
      comment{% if comments_total != 1 %}s{% endif %} on this article.
    </p>
    <p><a href="{% url 'blog:compose-comment' article.slug %}">
      Leave a comment
    </a></p>
    {% for comment in comments %}
    <div class="comment">
      {{ comment.body|markdown|safe }}
    <p><em>
      Comment left by {{ comment.name|escape|default:"anonymous" }} on
      {{ comment.created|date:"j M Y" }}
    </em></p>
    </div>
    {% endfor %}
    <footer>
      <hr />
      <a href="/">home</a>
      &gt;
      <a href="{% url 'blog:index' %}">blog</a>
    </footer>
  </body>
</html>

blog/templates/blog/comment-failed.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link href="/lunasspecto.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>hamster.dance comment submission</title>
  </head>
  <body>
    <p>
      Something went wrong with your comment submission. You may not have chosen the
      correct "spam" menu item, or something else might have gone wrong with the form.
    </p>
    <p><a href="{% url 'blog:compose-comment' article.slug %}">Try again</a></p>
  </body>
</html>

blog/templates/blog/comment-submitted.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link href="/lunasspecto.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>hamster.dance comment submission</title>
  </head>
  <body>
    <p>Your comment has been submitted and is awaiting manual approval. Thanks!</p>
    <p><a href="{% url 'blog:article' article.slug %}">Return to article</a></p>
  </body>
</html>

blog/templates/blog/compose-comment.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link href="/lunasspecto.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Commenting on: {{ article.title|striptags }}&mdash;hamster.dance blog</title>
  </head>
  <body>
    <h1>
        Commenting on article:
        <a href="{% url 'blog:article' article.slug %}">{{ article.title|safe }}</a>
    </h1>
    <p>
      Submit a comment using the form below. Please be very careful to choose the
      correct response from the "spam" dropdown menu below before submitting; otherwise
      your comment will be automatically discarded. All comments are subject to manual
      approval before they are published. Full use of
      <a href="https://www.markdownguide.org/basic-syntax/">Markdown</a> is permitted;
      however, your comments may be rejected or edited before publication if your
      formatting is deemed unreasonable. Criticism made in good faith is encouraged.
      Please reach out to 
      <a href="mailto:lunasspecto@hamster.dance">lunasspecto@hamster.dance</a> for any
      discussions you wouldn't want published on this web site.
    </p>
    <form action="{% url 'blog:submit-comment' article.slug %}" method="post">
      {% csrf_token %}
      <label for="body-input">Comment:</label>
      <br />
      <textarea
        id="body-input"
        name="body"
        minlength="1"
        maxlength="5096"
        required="true"
      ></textarea>
      <br />
      <label for="name-input">Name (optional):</label>
      <br />
      <input
        type="text"
        id="name-input"
        name="name"
        maxlength="256"
      />
      <br />
      <label for="spam-select">
          How much spam is in your comment?
      </label>
      <br />
      <select id="spam-select" name="spam">
        <option value="1">well, it hasn't got MUCH spam in it</option>
        <option value="2">spam, eggs, bacon &amp; spam</option>
        <option value="0">absolutely zero spam</option>
        <option value="3">spam, egg, spam, spam, bacon &amp; spam</option>
        <option value="4">spam spam spam spam spam spam spam spam</option>
      </select>
      <br />
      <input type="submit" value="Submit comment" />
    </form>
    <hr />
    <a href="/">home</a> &gt; <a href="{% url 'blog:index' %}">blog</a> &gt;
    <a href="{% url 'blog:article' article.slug %}">{{ article.title|safe }}</a>
  </body>
</html>

blog/templates/blog/index.html
{% load blog_extras %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link href="/lunasspecto.css" rel="stylesheet" />
    <link rel="alternate" type="application/rss+xml" title="hamster.dance blog articles" href="{% url 'blog:rss' %}" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>hamster.dance blog</title>
  </head>
  <body>
    <h1>hamster.dance blog</h1>
    {% for article in articles %}
    <a href="{% url 'blog:article' article.slug %}">
      <h2>{{ article.title|safe }}</h2>
    </a>
    <p><em>
      Published {{ article.published|date:"j M Y" }}
    </em></p>
    <p>{{ article.description }}</p>
    {% endfor %}
    <footer>
      <hr />
      {% if page_number > 1 %}
      <a href="{% url 'blog:page' previous_page %}">newer articles</a>
      {% endif %}
      {% if not last_page %}
      <a href="{% url 'blog:page' next_page %}">older articles</a>
      {% endif %}
      {% if page_number > 1 or not last_page %}
      <br />
      {% endif %}
      <a href="/">home</a>
    </footer>
  </body>
</html>

blog/templates/blog/tag.html
{% load blog_extras %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link href="/lunasspecto.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{{ tag.name }}&mdash;hamster.dance blog</title>
  </head>
  <body>
    <h1>hamster.dance blog articles tagged "{{ tag.name|escape }}"</h1>
    {% for article in articles %}
    <a href="{% url 'blog:article' article.slug %}">
      <h2>{{ article.title|safe }}</h2>
    </a>
    <p><em>
      Published {{ article.published|date:"j M Y" }}
    </em></p>
    <p>{{ article.description }}</p>
    {% endfor %}
    <footer>
      <hr />
      {% if page_number > 1 %}
      <a href="{% url 'blog:tag_page' tag.name previous_page %}">newer articles</a>
      {% endif %}
      {% if not last_page %}
      <a href="{% url 'blog:tag_page' tag.name next_page %}">older articles</a>
      {% endif %}
      {% if page_number > 1 or not last_page %}
      <br />
      {% endif %}
      <a href="/">home</a>
      &gt;
      <a href="{% url 'blog:index' %}">blog</a>
    </footer>
  </body>
</html>